events {} # The events block is used for configuring the event-driven architecture of NGINX

http {
  upstream backend {
    server api-gateway:8080;  # NGINX uses the Docker service name to resolve the backend container
  }

  server {
    listen 80;

    location / {
      proxy_pass http://backend;  # Forward traffic to the backend defined in the upstream section
      proxy_set_header Host $host; # Passes the original Host header (i.e., the domain name the client used to make the request).
      proxy_set_header X-Real-IP $remote_addr; # Passes the client's IP address, so the backend server knows the real IP of the client making the request
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # This adds the client's IP address to the X-Forwarded-For header
      proxy_set_header X-Forwarded-Proto $scheme; # Passes the protocol used by the client (either http or https)
    }
  }
}
